### ISSUE TITLE
Sqlite_async 0.7.0

### ISSUE THREAD

**Issue by RCVZ** [powersync-ja/drift_sqlite_async#3]
Could the package be updated to make it compatible with sqlite_async 0.7.0
So drift_sqlite_async is compatible with the latest powersync version.

**Comment by stevensJourney** [comment]
Hi @RCVZ. 

We are currently busy moving this package into a monorepo alongside `sqlite_async` - this should keep things more in sync. 

Can you maybe share some details of what the current issue you are experiencing with the current package?

**Comment by RCVZ** [comment]
Hi @stevensJourney 

I want to update powersync and sqlite_async to the latest version but drift_sqlite_async is incompatible with the latest version of sqlite_async.

Overriding the version doesn't seem like the way the go since sqlite_async has breaking changes.

**Comment by stevensJourney** [comment]
Thanks for the context! We'll release the updated packages early next week.

**Comment by mugikhan** [comment]
Hi @RCVZ we have released `drift_sqlite_async: 0.1.0-alpha.2` which uses the latest version of `sqlite_async`. Please update the package and let us know if you have any problems.

cc: @stevensJourney
